name = "Let's Create Everything"
author = "JayceTheGaymer & FroggieJonnie"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77dff8f94ae1bfeb966217b02c255431283d5265bb24fe3ad5693e0fd446a7ed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
