name = "Let's Create Everything"
author = "JayceTheGaymer & FroggieJonnie"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "602c9ed2af0199f6f43f5852b3e308505836e6d17b53454151f77ea914c07566"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
