name = "Let's Create Everything"
author = "JayceTheGaymer & FroggieJonnie"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "940723de7df8277d2fc1df969e228c6fe0349ca3e0cde868a914ad2942c40942"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
