// kubejsstudio recipes; re-apply merges by recipe id
ServerEvents.generateData('after_mods', event => {
    event.json('kubejs:recipe/iron_pickaxe_head', {"type":"create:compacting","ingredients":[{"item":"minecraft:iron_ingot"},{"item":"minecraft:iron_ingot"},{"item":"minecraft:iron_ingot"}],"results":[{"id":"jayces_tweaks:iron_pickaxe_head"}],"heat_requirement":"lowheated"})
    event.json('kubejsstudio:recipe/iron_axe_head', {"type":"create:compacting","ingredients":[{"item":"create:iron_sheet"},{"item":"minecraft:iron_ingot"}],"results":[{"id":"jayces_tweaks:iron_axe_head"}],"heat_requirement":"lowheated"})
    event.json('kubejsstudio:recipe/gold_backpack_new', {"type":"minecraft:crafting_shaped","category":"equipment","pattern":["###","#A#","#B#"],"key":{"#":{"tag":"c:ingots/gold"},"A":{"item":"sophisticatedbackpacks:iron_backpack"},"B":{"tag":"c:plates/gold"}},"result":{"id":"sophisticatedbackpacks:gold_backpack","count":1}})
    event.json('minecraft:recipe/diamond_from_blasting_deepslate_diamond_ore', {"type":"minecraft:blasting","group":"diamond","category":"misc","ingredient":{"tag":"c:ores/diamond"},"result":{"id":"minecraft:diamond"},"experience":1.0,"cookingtime":100})
    event.json('minecraft:recipe/diamond_from_smelting_deepslate_diamond_ore', {"type":"minecraft:smelting","group":"diamond","category":"misc","ingredient":{"tag":"c:ores/diamond"},"result":{"id":"minecraft:diamond"},"experience":1.0,"cookingtime":200})
})
ServerEvents.recipes(event => {
    event.shaped('minecraft:iron_axe', ['#', 'A'], { '#': 'jayces_tweaks:iron_axe_head', 'A': '#c:rods/wooden' }).id('kubejsstudio:iron_axe')
    event.shaped('createhorsepower:horse_crank', [' # ', 'ABA', 'CCC'], { '#': '#c:fences', 'A': 'create:andesite_alloy', 'B': 'create:shaft', 'C': 'minecraft:stone_slab' }).id('kubejsstudio:horse_crank')
    event.remove({ id: 'minecraft:wooden_pickaxe' })
    event.remove({ id: 'minecraft:wooden_axe' })
    event.remove({ id: 'createvintageneoforged:coiling/iron_spring' })
    event.remove({ id: 'createvintageneoforged:coiling/iron_rod' })
    event.remove({ id: 'createvintageneoforged:hammering/netherite_ingot' })
    event.shaped('createvintageneoforged:lathe', ['#A#', 'BBC', '#A#'], { '#': 'create:andesite_alloy', 'A': 'create:shaft', 'B': 'create:andesite_casing', 'C': '#c:storage_blocks/iron' }).id('kubejsstudio:mechanical_crafting/lathe')
    event.remove({ id: 'kubejsstudio:hammering/diamond_pickaxe' })
    event.shaped('minecraft:diamond_pickaxe', ['#', 'A'], { '#': 'jayces_tweaks:diamond_pickaxe_head', 'A': '#c:rods/wooden' }).id('kubejsstudio:diamond_pickaxe')
    event.remove({ id: 'minecraft:diamond_pickaxe' })
    event.shaped('minecraft:diamond_hoe', ['#', 'A'], { '#': 'jayces_tweaks:diamond_hoe_head', 'A': '#c:rods/wooden' }).id('kubejsstudio:diamond_hoe')
    event.shaped('minecraft:diamond_shovel', ['#', 'A'], { '#': 'jayces_tweaks:diamond_shovel_head', 'A': '#c:rods/wooden' }).id('kubejsstudio:diamond_shovel')
    event.shaped('minecraft:iron_sword', ['#', 'A'], { '#': 'jayces_tweaks:iron_sword_blade', 'A': '#c:rods/wooden' }).id('kubejsstudio:iron_sword')
    event.remove({ id: 'minecraft:diamond_hoe' })
    event.remove({ id: 'minecraft:diamond_axe' })
    event.remove({ id: 'minecraft:diamond_sword' })
    event.remove({ id: 'minecraft:diamond_shovel' })
    event.shaped('minecraft:diamond_sword', ['#', 'A'], { '#': 'jayces_tweaks:diamond_sword_blade', 'A': '#c:rods/wooden' }).id('kubejsstudio:diamond_sword')
})
