// kubejsstudio recipes; re-apply merges by recipe id
ServerEvents.generateData('after_mods', event => {
    event.json('kubejs:recipe/iron_pickaxe_head', {"type":"create:compacting","ingredients":[{"item":"minecraft:iron_ingot"},{"item":"minecraft:iron_ingot"},{"item":"minecraft:iron_ingot"}],"results":[{"id":"jayces_tweaks:iron_pickaxe_head"}],"heat_requirement":"lowheated"})
    event.json('kubejsstudio:recipe/iron_axe_head', {"type":"create:compacting","ingredients":[{"item":"create:iron_sheet"},{"item":"minecraft:iron_ingot"}],"results":[{"id":"jayces_tweaks:iron_axe_head"}],"heat_requirement":"lowheated"})
    event.json('kubejsstudio:recipe/gold_backpack_new', {"type":"minecraft:crafting_shaped","category":"equipment","pattern":["###","#A#","#B#"],"key":{"#":{"tag":"c:ingots/gold"},"A":{"item":"sophisticatedbackpacks:iron_backpack"},"B":{"tag":"c:plates/gold"}},"result":{"id":"sophisticatedbackpacks:gold_backpack","count":1}})
    event.json('minecraft:recipe/diamond_from_blasting_deepslate_diamond_ore', {"type":"minecraft:blasting","group":"diamond","category":"misc","ingredient":{"tag":"c:ores/diamond"},"result":{"id":"minecraft:diamond"},"experience":1.0,"cookingtime":100})
    event.json('minecraft:recipe/diamond_from_smelting_deepslate_diamond_ore', {"type":"minecraft:smelting","group":"diamond","category":"misc","ingredient":{"tag":"c:ores/diamond"},"result":{"id":"minecraft:diamond"},"experience":1.0,"cookingtime":200})
    event.json('createcasing:recipe/crafting/steam_engine/andesite', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#","A","B"],"key":{"#":{"tag":"c:plates/brass"},"A":{"item":"create:andesite_alloy"},"B":{"tag":"c:storage_blocks/andesite_alloy"}},"result":{"id":"createcasing:andesite_steam_engine","count":1}})
    event.json('createcasing:recipe/crafting/steam_engine/brass', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#","A","B"],"key":{"#":{"tag":"c:plates/brass"},"A":{"item":"create:andesite_alloy"},"B":{"tag":"c:storage_blocks/brass"}},"result":{"id":"createcasing:brass_steam_engine","count":1}})
    event.json('createcasing:recipe/crafting/steam_engine/zinc', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#","A","B"],"key":{"#":{"tag":"c:plates/brass"},"A":{"item":"create:andesite_alloy"},"B":{"tag":"c:storage_blocks/zinc"}},"result":{"id":"createcasing:zinc_steam_engine","count":1}})
})
ServerEvents.recipes(event => {
    event.remove({ id: 'kubejsstudio:mechanical_crafting/helve_hammer' })
    event.shaped('minecraft:iron_axe', ['#', 'A'], { '#': 'jayces_tweaks:iron_axe_head', 'A': '#c:rods/wooden' }).id('kubejsstudio:iron_axe')
    event.shaped('createhorsepower:horse_crank', [' # ', 'ABA', 'CCC'], { '#': '#c:fences', 'A': 'create:andesite_alloy', 'B': 'create:shaft', 'C': 'minecraft:stone_slab' }).id('kubejsstudio:horse_crank')
    event.remove({ id: 'minecraft:wooden_pickaxe' })
    event.remove({ id: 'minecraft:wooden_axe' })
    event.remove({ id: 'createvintageneoforged:coiling/iron_spring' })
    event.remove({ id: 'createvintageneoforged:coiling/iron_rod' })
    event.remove({ id: 'createvintageneoforged:hammering/netherite_ingot' })
    event.shaped('createvintageneoforged:lathe', ['#A#', 'BBC', '#A#'], { '#': 'create:andesite_alloy', 'A': 'create:shaft', 'B': 'create:andesite_casing', 'C': '#c:storage_blocks/iron' }).id('kubejsstudio:mechanical_crafting/lathe')
    event.shaped('minecraft:diamond_pickaxe', ['#', 'A'], { '#': 'jayces_tweaks:diamond_pickaxe_head', 'A': '#c:rods/wooden' }).id('kubejsstudio:diamond_pickaxe')
    event.remove({ id: 'minecraft:diamond_pickaxe' })
    event.shaped('minecraft:diamond_hoe', ['#', 'A'], { '#': 'jayces_tweaks:diamond_hoe_head', 'A': '#c:rods/wooden' }).id('kubejsstudio:diamond_hoe')
    event.shaped('minecraft:diamond_shovel', ['#', 'A'], { '#': 'jayces_tweaks:diamond_shovel_head', 'A': '#c:rods/wooden' }).id('kubejsstudio:diamond_shovel')
    event.shaped('minecraft:iron_sword', ['#', 'A'], { '#': 'jayces_tweaks:iron_sword_blade', 'A': '#c:rods/wooden' }).id('kubejsstudio:iron_sword')
    event.remove({ id: 'minecraft:diamond_hoe' })
    event.remove({ id: 'minecraft:diamond_axe' })
    event.remove({ id: 'minecraft:diamond_sword' })
    event.remove({ id: 'minecraft:diamond_shovel' })
    event.shaped('minecraft:diamond_sword', ['#', 'A'], { '#': 'jayces_tweaks:diamond_sword_blade', 'A': '#c:rods/wooden' }).id('kubejsstudio:diamond_sword')
    event.remove({ id: 'create:crafting/kinetics/water_wheel' })
    event.remove({ id: 'create:crafting/kinetics/large_water_wheel' })
    event.shaped('create:water_wheel', ['#A#', 'ABA', '#A#'], { '#': '#c:plates/andesite_alloy', 'A': '#minecraft:planks', 'B': 'create:cogwheel' }).id('kubejsstudio:water_wheel_new')
    event.shaped('create:large_water_wheel', ['#A#', 'ABA', '#A#'], { '#': 'tfmg:cast_iron_sheet', 'A': '#minecraft:planks', 'B': 'create:water_wheel' }).id('kubejsstudio:large_water_wheel_new')
    event.remove({ id: 'create:crafting/kinetics/windmill_bearing' })
    event.shaped('create:windmill_bearing', [' # ', 'ABA', 'ACA'], { '#': '#minecraft:wooden_slabs', 'A': 'tfmg:cast_iron_sheet', 'B': 'create:andesite_casing', 'C': 'create:shaft' }).id('kubejsstudio:windmill_bearing_new')
    event.remove({ id: 'create_sa:copper_pickaxe_recipe' })
    event.remove({ id: 'create_sa:copper_sword_recipe' })
    event.remove({ id: 'create_sa:copper_axe_recipe' })
    event.remove({ id: 'create_sa:copper_shovel_recipe' })
    event.remove({ id: 'create_sa:copper_hoe_recipe' })
    event.remove({ id: 'createvintageneoforged:mechanical_crafting/helve_hammer' })
    event.shaped('createvintageneoforged:helve_hammer', ['  #', 'ABB', 'A #'], { '#': '#c:ingots/andesite_alloy', 'A': '#c:storage_blocks/iron', 'B': '#minecraft:logs' }).id('kubejsstudio:helve_hammer')
    event.shaped('create:empty_blaze_burner', [' # ', '#A#', ' # '], { '#': '#c:plates/cast_iron', 'A': '#c:netherracks' }).id('kubejsstudio:empty_blaze_burner')
    event.remove({ id: 'create:crafting/kinetics/empty_blaze_burner' })
})
